---
title: "R Notebook"
output: html_notebook
---

```{r}
#install.packages("XML")
library(XML)
library(data.table)

xmlFile <- "Books-v3.xml"
fp <- paste0(path,xmlFile)

df <- xmlToDataFrame(fp, stringsAsFactors = FALSE)
xmlObj <- xmlParse(fp)

head(df)
```
1.
titles of books written by Galos, Mike
```{r}
  q2 <- "//book[author='Galos, Mike']/title"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```
prices of books written by Galos, Mike
```{r}
  q2 <- "//book[author='Galos, Mike']/price"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```
2.
```{r}
  q2 <- "//book[@id='bk109']/genre"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```
3.
```{r}
  q2 <- "//book[price=min(//book/price)]/title"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```

4.
titles of books in the Computer genre
```{r}
  q2 <- "//book[genre='Computer']/title"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```

prices of books in the Computer genre
```{r}
  q2 <- "//book[genre='Computer']/price"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```

5.
```{r}
  q2 <- "count(//book[price<5])"
  q2.apply <- xpathSApply(xmlObj, q2, xmlValue)
  head(q2.apply)
```


